# workflow name
name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the wanted branches
on:
  pull_request:
  push:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Remove unsupported versions and add more versions. Use LTR version in the cov_tests job
        docker_tags: [release-3_22,release-3_28, latest]
      fail-fast: false

    container:
      image: qgis/qgis:${{ matrix.docker_tags }}
      env:
        QGIS_PLUGIN_IN_CI: 1
        PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          apt-get update
          pip3 install -r requirements.txt

      - name: Run Tests
        run: xvfb-run -s '+extension GLX -screen 0 1024x768x24' python3 -m pytest -v


  windows_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        qgis_version: ['3.22.0','3.40.0']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Choco install qgis
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install qgis --version=${{ matrix.qgis_version }} -y

      - name: Setup Environmment
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS ${{ matrix.qgis_version }}\bin;$env:PATH"
          python-qgis.bat -m pip install -r requirements.txt


      - name: Run Tests
        shell: pwsh
        run: |
          $env:PATH="C:\Program Files\QGIS ${{ matrix.qgis_version }}\bin;$env:PATH"
          python-qgis.bat -m pytest -v

